@WebApiSample_HostAddress = http://localhost:5170
@ProductResourceName = Product

GET {{WebApiSample_HostAddress}}/api/{{ProductResourceName}}
Accept: application/json

###

GET {{WebApiSample_HostAddress}}/api/v2/{{ProductResourceName}}?page=1&pageSize=2
Accept: application/json

###

POST {{WebApiSample_HostAddress}}/api/{{ProductResourceName}}
Content-Type: application/json
Accept: application/json

{
  "name": "Další produkt",
  "price": 15,
  "imgUri": "https://media.gettyimages.com/id/1327018520/photo/a-capitol-fourth.jpg?s=2048x2048&w=gi&k=20&c=zC8cNQd8OSOTwhSnEfcrmhx5z5shWxy4fhZNuGmRfeE=",
  "description": "Popis dalšího produktu"
}

###

DELETE {{WebApiSample_HostAddress}}/api/{{ProductResourceName}}/3
Accept: application/json

###

PATCH {{WebApiSample_HostAddress}}/api/{{ProductResourceName}}
Content-Type: application/json
Accept: application/json

{
  "id": 2,
  "description": "Nový popis"
}

###