@WebApiSample_HostAddress = http://localhost:5170

GET {{WebApiSample_HostAddress}}/api/Product
Accept: application/json

###

GET {{WebApiSample_HostAddress}}/api/Product/1
Accept: application/json

###

POST {{WebApiSample_HostAddress}}/api/Product
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "name": "Další produkt",
  "price": 15,
  "imgUri": "https://media.gettyimages.com/id/1327018520/photo/a-capitol-fourth.jpg?s=2048x2048&w=gi&k=20&c=zC8cNQd8OSOTwhSnEfcrmhx5z5shWxy4fhZNuGmRfeE=",
  "description": "Popis dalšího produktu"
}

###

DELETE {{WebApiSample_HostAddress}}/api/Product/3
Accept: application/json

###

PUT {{WebApiSample_HostAddress}}/api/Product/2/description
Content-Type: application/json
Accept: application/json

{
  "id": 2,
  "description": "Nový popis"
}

###